dist: trusty
sudo: false

addons:
  apt:
    packages:
      - cmake

language: cpp

install:
    - rm -rf build
    - mkdir build
    - cd build
    - cmake ../src && make -j
    - cd ../bin

script: ./tests_all