dist: trusty
sudo: true

addons:
  apt:
    packages:
      - cmake
      - libgtest-dev

language: cpp

install:
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - cd $TRAVIS_BUILD_DIR
    - mkdir build
    - cd build
    - cmake ../src && make -j
    - cd ../bin

script: ./test_all
