dist: trusty
sudo: true

addons:
  apt:
    packages:
      - cmake
      - libgtest-dev

language: cpp

#before_install:
    #    - pip install --user cpp-coveralls

install:
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt -DCOVERAGE=1
    - sudo make
    - sudo cp *.a /usr/lib
    - cd $TRAVIS_BUILD_DIR
    - mkdir build
    - cd build
    - cmake ../src && make -j
    - cd ../bin

script: 
    - ./test_all

after_success:
    # - coveralls --root . -E ".*gtest.*" -E ".*CMakeFile*CMakeFiless."
    - bash <(curl -s https://codecov.io/bash)
